#!/usr/bin/env python3
"""
Test script to demonstrate the rule-based commentary system.
Shows example outputs without needing to run the full server.
"""
import asyncio
from app.ai_engine import ai_live_commentary, ai_mendoza_watch, ai_winprob_explain, ai_postgame_recap


async def demo_commentary():
    print("\n" + "="*80)
    print("RULE-BASED COMMENTARY EXAMPLES")
    print("="*80)
    print("\n✅ No API key needed! All commentary generated by intelligent rules.\n")
    
    # Scenario 1: Close game in 4th quarter
    print("="*80)
    print("SCENARIO 1: Close Game - 4th Quarter")
    print("="*80)
    state1 = {
        "home_team": "Miami",
        "away_team": "Indiana",
        "home_score": 24,
        "away_score": 21,
        "quarter": 4,
        "clock": "8:42",
        "status": "live",
        "mendoza": {
            "pass_yds": 287,
            "td": 3,
            "int": 1
        }
    }
    
    commentary = await ai_live_commentary({"state": state1})
    print(f"\n📢 Live Commentary:\n   {commentary}\n")
    
    mendoza = await ai_mendoza_watch(state1)
    print(f"🎯 Player Analysis:\n   {mendoza}\n")
    
    winprob_explain = await ai_winprob_explain(state1, 0.68)
    print(f"📊 Win Probability:\n   Miami 68% — {winprob_explain}\n")
    
    # Scenario 2: Blowout in 3rd quarter
    print("="*80)
    print("SCENARIO 2: Blowout - 3rd Quarter")
    print("="*80)
    state2 = {
        "home_team": "Ohio State",
        "away_team": "Penn State",
        "home_score": 35,
        "away_score": 10,
        "quarter": 3,
        "clock": "5:23",
        "status": "live",
        "mendoza": {
            "pass_yds": 412,
            "td": 4,
            "int": 0
        }
    }
    
    commentary = await ai_live_commentary({"state": state2})
    print(f"\n📢 Live Commentary:\n   {commentary}\n")
    
    mendoza = await ai_mendoza_watch(state2)
    print(f"🎯 Player Analysis:\n   {mendoza}\n")
    
    winprob_explain = await ai_winprob_explain(state2, 0.95)
    print(f"📊 Win Probability:\n   Ohio State 95% — {winprob_explain}\n")
    
    # Scenario 3: Tied game at halftime
    print("="*80)
    print("SCENARIO 3: Tied Game - Halftime")
    print("="*80)
    state3 = {
        "home_team": "Michigan",
        "away_team": "Alabama",
        "home_score": 14,
        "away_score": 14,
        "quarter": 2,
        "clock": "0:00",
        "status": "live",
        "mendoza": {
            "pass_yds": 156,
            "td": 1,
            "int": 0
        }
    }
    
    commentary = await ai_live_commentary({"state": state3})
    print(f"\n📢 Live Commentary:\n   {commentary}\n")
    
    mendoza = await ai_mendoza_watch(state3)
    print(f"🎯 Player Analysis:\n   {mendoza}\n")
    
    winprob_explain = await ai_winprob_explain(state3, 0.50)
    print(f"📊 Win Probability:\n   Even 50% — {winprob_explain}\n")
    
    # Scenario 4: Postgame recap
    print("="*80)
    print("SCENARIO 4: Postgame Recap")
    print("="*80)
    final_state = {
        "home_team": "Texas",
        "away_team": "Oklahoma",
        "home_score": 28,
        "away_score": 24,
        "quarter": 4,
        "status": "final"
    }
    
    mendoza_history = ["287 passing yards, 3 TD, 1 INT. Solid production through the air. More positives than negatives."]
    winprob_history = []
    
    recap = await ai_postgame_recap(final_state, winprob_history, mendoza_history)
    print(f"\n🏁 Postgame Recap:\n   {recap}\n")
    
    # Summary
    print("="*80)
    print("SUMMARY")
    print("="*80)
    print("""
The commentary system analyzes:
- Score differential (margin analysis)
- Game quarter (time context)
- Game situation (crunch time vs early)
- Player efficiency (yards per attempt)
- Ball security (TD/INT ratio)

All generated instantly with zero API costs!

To see this in action with live games:
1. python find_live_games.py
2. Create .env with ESPN_GAME_ID
3. uvicorn app.main:app --reload
""")


if __name__ == "__main__":
    asyncio.run(demo_commentary())
